Filter offers with minimal cpus requirement for each role
criteo-forks/mesos pull request #60
Opened 2021-07-28 13:28 UTC by djdhm

Added a new flag to activate this feature 'min_offerable_filter' default value is false.
When filtering offers for a role , verify that the cpus available is greater than the previously declined offers.
This PR is to resolve the issue reported in PROD clusters , Schedulability of tasks where impossible for some roles ( MESOS-5117) 
For More information :https://confluence.criteois.com/display/~d.dahmane/Mesos+Fragmentation+Internship

2021-07-28 13:55 UTC, St0rmingBr4in submitted a review, later dismissed

2021-07-28 13:55 UTC, St0rmingBr4in commented on src/master/allocator/mesos/hierarchical.cpp
> +  if (!isOfferable(framework, role, resources)) {
The feature gate should be put there instead of on the isOfferable var.

2021-07-28 13:55 UTC, St0rmingBr4in commented on src/master/allocator/mesos/hierarchical.cpp
> +  if( options.minOfferableFilter){
Pay attention to the coding style used. There are a lot of coding style issues. I am surprised we don't have a linter running on the code.

2021-07-28 13:55 UTC, St0rmingBr4in commented on src/master/allocator/mesos/hierarchical.cpp
> +      return resources.cpus().getOrElse(0) >  minimumCpus;
Sad We hardcode the behavior for the cpu ressource only. It will only work if the cpu_first slave sorter is activated so you should abort if it is not activated as well.

2021-07-29 13:06 UTC, djdhm commented on src/master/allocator/mesos/hierarchical.cpp
> +      return resources.cpus().getOrElse(0) >  minimumCpus;
we can externalize the function into the Slaves sorter to make the filtering logic defined by the slave sorter , The feature could be activated by choosing another sorter like : "cpu_first_with_filter".

2021-07-29 13:08 UTC, djdhm commented on src/master/allocator/mesos/hierarchical.cpp
> +  if (!isOfferable(framework, role, resources)) {
I think making the filtering function defined in the slaves sorter will prevent this issue, and that will be replaced by a call to the function defined in the slave sorter "slavesorter->isOfferable"

2021-07-29 13:17 UTC, djdhm commented on src/master/allocator/mesos/hierarchical.cpp
> +  if( options.minOfferableFilter){
The style used in Mesos is Google C++ style guide, I configured the linter to prevent future style issues

2021-07-29 15:30 UTC, St0rmingBr4in commented on src/master/allocator/mesos/hierarchical.cpp
> +      return resources.cpus().getOrElse(0) >  minimumCpus;
Yes good idea.

2021-08-04 09:13 UTC, Lqp1 commented
> Added a new filter for offers to verify that the resources are greater than the last one declined to prevent sending a lot of offers with same resources , the logic of filtering is implemented in the slaves sorter, for the cpu_first slaves sorter ,the filter verify that the cpus offered are greater than the cpus in previously declined offers.

What if previous offers were declined because of another reason? like other ressources (memory/gpu), or a constraint (maintenance groups, canary/host bound/etc...) ? are we not going to send larger offers for nothing?

> This PR is to resolve the issue reported in PROD clusters , Schedulability of tasks where impossible for some roles ( MESOS-5117)

I did not follow exactly what happenned in prod but I'm not sure how this would solve the issue ? (I don't see the explanation of what happened in the ticket). Can you explain it a bit more please?

I was thinking that if an offer is declined, the same one won't be sent again for some time, so it should not cause that kind of issue, no ?

2021-08-04 09:41 UTC, djdhm commented
> I did not follow exactly what happenned in prod but I'm not sure how this would solve the issue ? (I don't see the explanation of what happened in the ticket). Can you explain it a bit more please?

The issue encountered on AM5 prod dc is explained in this confluence page  : https://confluence.criteois.com/display/SCS/2021-07-20+Schedulability+of+tasks+on+marathon+is+much+slower+than+usual
When investigating the logs , the problem was that the marathons were receiving a lot of offers with not enough cpus and that was due to the slaves sorting with cpus available.

2021-08-04 09:49 UTC, djdhm commented
> I was thinking that if an offer is declined, the same one won't be sent again for some time, so it should not cause that kind of issue, no ?

Yes if an offer is declined it won't be sent again for some time but other offers with same cpus are sent, and before reaching the slaves with enough cpus the timeout of offer declined filter is reached what make the allocator send again this offers , 
The filter is to prevent sending all offers with same cpus quantity to the last one declined to make the allocator quickly send agents that have enough cpus, since we have the agents sorted based on cpus availabe

2021-08-04 11:49 UTC, Lqp1 commented
Ok thanks, the "why" is clearer now (i'm not sure there are as much details on confluence).

However I don't feel very comfortable having such an impacting change without any way to rollback easily (there should be a flag or something to disable this quickly), as for the previous test (we were happy to have it in prod :p ).

2021-08-04 11:50 UTC, Lqp1 requested changes
Let's make this new behavior optin or optout, so that we can easily go back to defaults, and enable it on some DCs/ENVs only

2021-08-04 12:19 UTC, djdhm commented
> Let's make this new behavior optin or optout, so that we can easily go back to defaults, and enable it on some DCs/ENVs only

this feature is already an option included in the slaves sorter, the default behavior is to accept all offers and the implementation is inside the cpu_first sorter and deactivating the cpu sorter will make this feature deactivated 
I don't know if we will need to activate the cpu first without this feature because it was proved not working already

2021-08-04 12:19 UTC, Lqp1 commented
oh I see! great

2021-08-04 12:20 UTC, Lqp1 approved these changes

2021-08-04 12:20 UTC, merged